# Removes orchestrator-internal sandbox-prep receipt files from all goal worktrees.
# Interim tool while the receipt is excluded from cleanliness checks (fix in flight);
# safe: receipts are regenerated by the idempotent prep on next dispatch.
# Usage: ./scripts/Clear-PrepReceipts.ps1
$worktrees = Join-Path (Split-Path $PSScriptRoot -Parent) '.orchestrator-worktrees'
Get-ChildItem $worktrees -Directory -ErrorAction SilentlyContinue | ForEach-Object {
    $receipt = Join-Path $_.FullName '.mcg-sandbox-prep-receipt-v1.json'
    if (Test-Path $receipt) {
        Remove-Item $receipt
        $_.Name
    }
}
