global using Mcg.AgentOrchestrator.App.Application;
global using Mcg.AgentOrchestrator.App.Cli;
global using Mcg.AgentOrchestrator.App.CostControl;
global using Mcg.AgentOrchestrator.App.Dashboard.Api;
global using Mcg.AgentOrchestrator.App.Dashboard.Hosting;
global using Mcg.AgentOrchestrator.App.Dashboard.Rendering;
global using Mcg.AgentOrchestrator.App.Orchestration;
global using Mcg.AgentOrchestrator.App.Providers;
global using Mcg.AgentOrchestrator.App.Prototype;
global using Mcg.AgentOrchestrator.App.SubscriptionPlanning;
global using Mcg.AgentOrchestrator.Core;
global using Mcg.AgentOrchestrator.Infrastructure;
global using DashboardApplicationServices = Mcg.AgentOrchestrator.App.Hosting.OptionalHostApplicationServices;
global using ConsoleViews = Mcg.AgentOrchestrator.App.Hosting.OptionalHostApplicationServices;
